#!/bin/bash

# Request one node that will not be allocated to others for the duration of the run.
#SBATCH -N1 --exclusive --ntasks-per-node=40 -t 01-23:00:00
#SBATCH -C skylake
#SBATCH -o out/%j.out
#SBATCH --mem-per-cpu=5000
#SBATCH --mail-user=kvantilburg@flatironinstitute.org
#SBATCH --mail-type=ALL
#SBATCH --requeue

# Activate conda environment
source ~/.bashrc
conda activate luminous-basin

jmock=6

# Run 
for ip in {0..400..1}
    do
        for im in {21..369..1}
            do
                echo "Starting projection $jmock $im"
                mkdir /mnt/home/kvantilburg/ceph/luminous-basin/results/data/proj/proj_$ip/
                srun -n1 -c1 --mem-per-cpu=5000 python3 script_12_yellin_proj_data.py $ip $im &
                sleep 1
            done
    done

# set 'wait' barrier so entire job does not get killed when last srun command does
echo "All projections started"
wait 
echo "All projections finished"
